# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kazi-org/dira/releases/download/v0.1.1/dira_0.1.1_darwin_arm64.tar.gz"
      sha256 "7c9b62f58be5b5775315f957c676343fee03e7c0e322c83093d64388c70d1e38"
    end
    on_intel do
      url "https://github.com/kazi-org/dira/releases/download/v0.1.1/dira_0.1.1_darwin_amd64.tar.gz"
      sha256 "bd1100a65fa0c77e732b020227e55c2522bf02a81a65ca254cc600279a3258fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kazi-org/dira/releases/download/v0.1.1/dira_0.1.1_linux_amd64.tar.gz"
      sha256 "7e5430afa7bd0a8d515f380c37c1fd69e2f1f189a055048adefe315742641d02"
    end
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
