# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/kazi-org/dira/releases/download/v0.1.0/dira_0.1.0_darwin_arm64.tar.gz"
    sha256 "baf6eb74e99a3dd71628d48cba709ff2d34741575075edfa42fc20060d66b115"
  end

  on_linux do
    url "https://github.com/kazi-org/dira/releases/download/v0.1.0/dira_0.1.0_linux_amd64.tar.gz"
    sha256 "2f7772996d798594b8b84caf962c55ddcf80be0d3cacdcc517feb1dfce489b79"
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
