# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kazi-org/dira/releases/download/v0.2.0/dira_0.2.0_darwin_arm64.tar.gz"
      sha256 "bfbd221b404ff1b9a3938152d2589fae77b436209b5d3b08cd9bf39796fba1c1"
    end
    on_intel do
      url "https://github.com/kazi-org/dira/releases/download/v0.2.0/dira_0.2.0_darwin_amd64.tar.gz"
      sha256 "81cf7aff5d8811cd65b3d1dc67f127261f515b2aa45e0e0e2d3b28fc8da59eb5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kazi-org/dira/releases/download/v0.2.0/dira_0.2.0_linux_amd64.tar.gz"
      sha256 "9da0690284561345df72117287338b57a6aa517a18633a82debeb881b0bf5057"
    end
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
