# Generated by the kazi release pipeline (ADR-0017). Do not hand-edit.
class Kazi < Formula
  desc "Reconciliation controller that drives a coding agent until goal predicates are true"
  homepage "https://github.com/kazi-org/kazi"
  version "1.99.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.99.0/kazi_macos_aarch64"
      sha256 "5cf383970be2581a20db63b92da2c183691cb7659ff60882af3fe3b7f1b6fc05"
    end
    on_intel do
      url "https://github.com/kazi-org/kazi/releases/download/v1.99.0/kazi_macos_x86_64"
      sha256 "2bc6436236eff86968437ee244082d327fa2c6e22a0c2a5cbc7e89cca6a37041"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kazi-org/kazi/releases/download/v1.99.0/kazi_linux_x86_64"
      sha256 "5bc15999abb4bd89b4e23590aebb697f4fb064ec0241d5d3c4541f3673cf8b0c"
    end
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.99.0/kazi_linux_aarch64"
      sha256 "7c9cdc4e0231732c6e084a2852bb159d90fcac3b477678fac9b7b20f8e042744"
    end
  end

  def install
    bin.install Dir["kazi_*"].first => "kazi"
  end

  test do
    assert_match "kazi", shell_output("#{bin}/kazi --help")
  end
end
