# Generated by the kazi release pipeline (ADR-0017). Do not hand-edit.
class Kazi < Formula
  desc "Reconciliation controller that drives a coding agent until goal predicates are true"
  homepage "https://github.com/kazi-org/kazi"
  version "1.96.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.96.0/kazi_macos_aarch64"
      sha256 "4c1b42338b66c96387c860f051bfc7c40f37957f86e434a1456ea6bc31cd3a8e"
    end
    on_intel do
      url "https://github.com/kazi-org/kazi/releases/download/v1.96.0/kazi_macos_x86_64"
      sha256 "21b839869a160c937381e8617b43e7bfc676e34ea2d10f906a5498980b5a6727"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kazi-org/kazi/releases/download/v1.96.0/kazi_linux_x86_64"
      sha256 "d0dc960bed4b7cc6d47ba5dc5367bf658330a7b203cda8b0e72d18c38f8a2d8e"
    end
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.96.0/kazi_linux_aarch64"
      sha256 "c162d5630b875ac9d641216add0e93ba63c818cba6cfedbee76780b7b2b6029d"
    end
  end

  def install
    bin.install Dir["kazi_*"].first => "kazi"
  end

  test do
    assert_match "kazi", shell_output("#{bin}/kazi --help")
  end
end
