# Generated by the kazi release pipeline (ADR-0017). Do not hand-edit.
class Kazi < Formula
  desc "Reconciliation controller that drives a coding agent until goal predicates are true"
  homepage "https://github.com/kazi-org/kazi"
  version "1.73.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.73.3/kazi_macos_aarch64"
      sha256 "b3affc55f203c0bc16fc3b3c99e7629b0a36f9ce239d48a25380ae943986ceec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kazi-org/kazi/releases/download/v1.73.3/kazi_linux_x86_64"
      sha256 "35adc8b5db68af5f9d05890496c56e33fb6d33fefdcd5f74b78c7e500373b0f5"
    end
    on_arm do
      url "https://github.com/kazi-org/kazi/releases/download/v1.73.3/kazi_linux_aarch64"
      sha256 "0a253e5c697a76b455c82cf7378cc89e7e3f833d9cbc41d81274758fa83d0dc7"
    end
  end

  def install
    bin.install Dir["kazi_*"].first => "kazi"
  end

  test do
    assert_match "kazi", shell_output("#{bin}/kazi --help")
  end
end
