# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprintd < Formula
  desc "Token-free scheduler that dispatches deadline-bounded agent lanes and verifies them with acceptance predicates"
  homepage "https://github.com/kazi-org/sprintd"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.5.0/sprintd_0.5.0_darwin_amd64.tar.gz"
      sha256 "bcd2419c14221c9063771b562090b406da6153b555611ada538a870c7bc0fec0"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.5.0/sprintd_0.5.0_darwin_arm64.tar.gz"
      sha256 "ce0b2752d17302a834342fca3704f27ed6ab04f065365bb852c6a7a62b754f3a"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.5.0/sprintd_0.5.0_linux_amd64.tar.gz"
      sha256 "9cbb12cc05987104ceb98c115044a1466f5fea20f941123285688e00fa6ff66d"
      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  test do
    assert_match "sprintd", shell_output("#{bin}/sprintd version")
  end
end
