# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Sprintd < Formula
  desc "Token-free scheduler that dispatches deadline-bounded agent lanes and verifies them with acceptance predicates"
  homepage "https://github.com/kazi-org/sprintd"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.3/sprintd_0.1.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42b471b9bf3d8128652a36b72725b83d9bb520b869c4249a4dbeca6b1ac8efa6"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.3/sprintd_0.1.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e2b7565215345e833ab00de88970a2667ddb43c4577df57d3824791748669b05"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.3/sprintd_0.1.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "19db26bd9c19e5eed3a6c5675745ddc1316733edde25686ae9ba66cf6ca4f32b"
      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  test do
    assert_match "sprintd", shell_output("#{bin}/sprintd version")
  end
end
