# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprintd < Formula
  desc "Token-free scheduler that dispatches deadline-bounded agent lanes and verifies them with acceptance predicates"
  homepage "https://github.com/kazi-org/sprintd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.0/sprintd_0.1.0_darwin_amd64.tar.gz"
      sha256 "68e00a7fced4a2cfe81b709fd73c424c2105f51fd903ef00be6ca6822dcc2603"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.0/sprintd_0.1.0_darwin_arm64.tar.gz"
      sha256 "eeb11d11d027e8aefd201e210f5a0c59821823b69c9a8db2ed5c0259f9b21d40"

      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kazi-org/sprintd/releases/download/v0.1.0/sprintd_0.1.0_linux_amd64.tar.gz"
      sha256 "238a7ceefc7f82a48fa542785861f8b7bc15069d98edf58ce008a46304a743fc"
      define_method(:install) do
        bin.install "sprintd"
      end
    end
  end

  test do
    assert_match "sprintd", shell_output("#{bin}/sprintd version")
  end
end
